name: moment
description: Frontend of Moment TCE

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  curved_navigation_bar: ^1.0.1
  dotted_border: ^2.0.0+2
  file_picker: ^4.3.1
  firebase_core: ^1.11.0
  firebase_messaging: ^11.2.5
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.2.0
  http: ^0.13.4
  provider: ^6.0.2
  shared_preferences: ^2.0.11

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: BerkshireSwash
      fonts:
        - asset: assets/fonts/BerkshireSwash-Regular.ttf
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
