name: moment
description: Frontend of Moment TCE

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  curved_navigation_bar: ^1.0.1
  dotted_border: ^2.0.0+2
  file_picker: ^4.3.1
  firebase_core: ^1.16.0
  firebase_messaging: ^11.3.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.5.2
  http: ^0.13.4
  open_file: ^3.2.1
  path_provider: ^2.0.9
  provider: ^6.0.2
  permission_handler: ^9.2.0
  shared_preferences: ^2.0.11
  cached_network_image: ^3.2.0
  photo_view: ^0.13.0
  flutter_linkify: ^5.0.2
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: BerkshireSwash
      fonts:
        - asset: assets/fonts/BerkshireSwash-Regular.ttf
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf

dependency_overrides:
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: 8156907eecfa812b181a5a729d790f6d399f311b
